// Generate local HA branding and the sidebar icon from the panel's vector geometry.
// Run after: cd frontend && npm ci && npx playwright install chromium
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const require = createRequire(new URL("frontend/package.json", root));
const { chromium } = require("@playwright/test");
const mark = JSON.parse(
  await readFile(new URL("frontend/src/brand.json", root)),
);
const svg = (ink, accent) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${mark.viewBox}"><path fill="${ink}" d="${mark.rings}"/><path fill="${accent}" d="${mark.radius}"/></svg>`;

for (const dir of [
  "frontend/public",
  "docs/brand",
  "custom_components/blast_radius/brand",
]) {
  await mkdir(new URL(dir, root), { recursive: true });
}
const light = svg("#25313b", "#bd7400");
const dark = svg("#edf1f4", "#f2b544");
await writeFile(new URL("docs/brand/icon.svg", root), light + "\n");
await writeFile(new URL("docs/brand/dark-icon.svg", root), dark + "\n");
await writeFile(
  new URL("frontend/public/blast-radius-icons.js", root),
  `// Generated by scripts/generate_brand.mjs; source: frontend/src/brand.json.\n` +
    `window.customIconsets = window.customIconsets || {};\n` +
    `window.customIconsets["blast-radius"] = async (name) => name === "radius" ? ` +
    JSON.stringify({
      path: `${mark.rings} ${mark.radius}`,
      viewBox: mark.viewBox,
    }) +
    ` : undefined;\n`,
);

const browser = await chromium.launch();
try {
  const page = await browser.newPage();
  for (const [theme, artwork] of [
    ["", light],
    ["dark_", dark],
  ]) {
    for (const size of [256, 512]) {
      await page.setViewportSize({ width: size, height: size });
      await page.setContent(
        `<style>html,body{margin:0;background:transparent}svg{display:block;width:100%;height:100%}</style>${artwork}`,
      );
      await page.screenshot({
        path: fileURLToPath(
          new URL(
            `custom_components/blast_radius/brand/${theme}icon${size === 512 ? "@2x" : ""}.png`,
            root,
          ),
        ),
        omitBackground: true,
      });
    }
  }
  await page.setViewportSize({ width: 960, height: 360 });
  await page.setContent(
    `<style>
    *{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;display:flex}
    section{width:480px;height:360px;padding:36px 40px;background:#f7f8fa;color:#25313b}
    section+section{background:#171c22;color:#edf1f4}
    .mark{width:128px;height:128px;margin:0 0 30px}.mark svg{width:100%;height:100%}
    h1{font-size:21px;letter-spacing:-.5px;margin:0 0 8px;font-weight:600}
    p{margin:0;font-size:13px;opacity:.66;line-height:1.5}
    .small{float:right;display:flex;align-items:center;gap:22px;height:128px}
    .small svg:first-child{width:24px;height:24px}.small svg:last-child{width:40px;height:40px}
    </style>` +
      [light, dark]
        .map(
          (artwork) =>
            `<section><div class="small">${artwork}${artwork}</div><div class="mark">${artwork}</div><h1>HA Blast Radius</h1><p>Dependency &amp; impact analysis</p></section>`,
        )
        .join(""),
  );
  await page.screenshot({
    path: fileURLToPath(new URL("docs/brand/preview.png", root)),
  });
} finally {
  await browser.close();
}
console.log(
  "Generated vector marks, local HA icons and the sidebar icon module.",
);
